### ISSUE TITLE
redis.exceptions.ResponseError: chat_docs: no such index

### ISSUE THREAD

**Issue by vporton** [apssouza22/chatflow#37]
In the first run of the software as described in `README.md`:
```
INFO:     127.0.0.1:43206 - "POST /api/v1/docs/search HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/porton/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/porton/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/porton/.local/lib/python3.9/site-packages/fastapi/applications.py", line 284, in __call__
    await super().__call__(scope, receive, send)
  File "/home/porton/.local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/porton/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/porton/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/porton/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/porton/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/home/porton/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/porton/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/porton/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/porton/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/porton/.local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/porton/.local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/porton/.local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/porton/.local/lib/python3.9/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/home/porton/.local/lib/python3.9/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/porton/Projects/chatflow/server/src/api/docs.py", line 31, in find_docs
    return await doc_search_service.full_search(search_req)
  File "/home/porton/Projects/chatflow/server/src/core/docs_search/doc_service.py", line 34, in full_search
    results_vector = await self.vector_search.search_vectors(search_req.tags, vector_bytes)
  File "/home/porton/Projects/chatflow/server/src/core/docs_search/vector_search.py", line 22, in search_vectors
    return await self.conn.ft(self.index).search(query, query_params={"vec_param": vector})
  File "/home/porton/.local/lib/python3.9/site-packages/redis/commands/search/commands.py", line 889, in search
    res = await self.execute_command(SEARCH_CMD, *args)
  File "/home/porton/.local/lib/python3.9/site-packages/redis/asyncio/client.py", line 518, in execute_command
    return await conn.retry.call_with_retry(
  File "/home/porton/.local/lib/python3.9/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
    return await do()
  File "/home/porton/.local/lib/python3.9/site-packages/redis/asyncio/client.py", line 492, in _send_command_parse_response
    return await self.parse_response(conn, command_name, **options)
  File "/home/porton/.local/lib/python3.9/site-packages/redis/asyncio/client.py", line 539, in parse_response
    response = await connection.read_response()
  File "/home/porton/.local/lib/python3.9/site-packages/redis/asyncio/connection.py", line 810, in read_response
    raise response from None
redis.exceptions.ResponseError: chat_docs: no such index
```

**Comment by vporton** [comment]
It seems that this happens after restarting `docker-compose`.

So, it seems that I need to run `load_data.py` after every restart of `docker-compose`. I think, I should fix this error first.

**Comment by apssouza22** [comment]
@vporton No. You don't need to rerun load_data every restart
